### ISSUE TITLE
Introduce AsyncTaskInstance

### ISSUE THREAD

**Issue by bzafiris** [theod0sis/Reactiveness#1]
Εκτός από γνωρίσματα που αναπαριστούν την κλάση του AsyncTask (PsiFile), τον τύπο του, την κλάση που δηλώνει το AsyncTask ως inner κλάση, τα σημεία όπου καλείται το async task κτλ, στην `AsyncTaskInstance` μπορείς να μεταφέρεις λογική όπως αυτή:
https://github.com/theod0sis/Reactiveness/blob/d05bda7e66560701a44612259fdfde7ec75a349f/src/main/java/gr/aueb/reactiveness/refactor/AsyncTaskRefactor.java#L69

Συνεπώς, κάθε AsyncTaskInstance θα συλλέγει και θα καταγράφει όλη την πληροφορία που χρειάζεται για την πραγματοποίηση του refactoring. Η υλοποίηση του refactoring θα γίνεται σε τρίτη κλαση όπως συμβαίνει στην τρέχουσα έκδοση

**Comment by theod0sis** [comment]
Έγινε το παρακάτω commit για το issue αυτό: https://github.com/theod0sis/Reactiveness/commit/e7a4fb3cc1249b91bda58117b329749793a87385 .
